package net.seska.normality.util;

import net.fabricmc.fabric.api.object.builder.v1.block.type.WoodTypeRegistry;
import net.minecraft.block.BlockSetType;
import net.minecraft.block.WoodType;
import net.minecraft.util.Identifier;
import net.seska.normality.NormalityMod;

public class ModWoodTypes {
    public static final WoodType HOLLY_WOOD = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "holly_wood"), BlockSetType.OAK);
    public static final WoodType CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "chanterelle"), BlockSetType.OAK);
    public static final WoodType ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "enoki"), BlockSetType.OAK);
    public static final WoodType BLACK_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_birch"), BlockSetType.OAK);
    public static final WoodType BLUE_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_birch"), BlockSetType.OAK);
    public static final WoodType BROWN_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_birch"), BlockSetType.OAK);
    public static final WoodType CYAN_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_birch"), BlockSetType.OAK);
    public static final WoodType GRAY_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_birch"), BlockSetType.OAK);
    public static final WoodType GREEN_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_birch"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_birch"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_birch"), BlockSetType.OAK);
    public static final WoodType LIME_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_birch"), BlockSetType.OAK);
    public static final WoodType MAGENTA_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_birch"), BlockSetType.OAK);
    public static final WoodType ORANGE_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_birch"), BlockSetType.OAK);
    public static final WoodType PINK_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_birch"), BlockSetType.OAK);
    public static final WoodType PURPLE_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_birch"), BlockSetType.OAK);
    public static final WoodType RED_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_birch"), BlockSetType.OAK);
    public static final WoodType WHITE_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_birch"), BlockSetType.OAK);
    public static final WoodType YELLOW_BIRCH = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_birch"), BlockSetType.OAK);
    //BAMBOO
    public static final WoodType BLACK_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType BLUE_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType BROWN_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType CYAN_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType GRAY_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType GREEN_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType LIGHT_BLUE_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType LIGHT_GRAY_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType LIME_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType MAGENTA_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType ORANGE_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType PINK_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType PURPLE_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType RED_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType WHITE_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_bamboo"), BlockSetType.BAMBOO);
    public static final WoodType YELLOW_BAMBOO = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_bamboo"), BlockSetType.BAMBOO);
    //HOLLY
    public static final WoodType BLACK_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_holly"), BlockSetType.OAK);
    public static final WoodType BLUE_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_holly"), BlockSetType.OAK);
    public static final WoodType BROWN_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_holly"), BlockSetType.OAK);
    public static final WoodType CYAN_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_holly"), BlockSetType.OAK);
    public static final WoodType GRAY_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_holly"), BlockSetType.OAK);
    public static final WoodType GREEN_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_holly"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_holly"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_holly"), BlockSetType.OAK);
    public static final WoodType LIME_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_holly"), BlockSetType.OAK);
    public static final WoodType MAGENTA_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_holly"), BlockSetType.OAK);
    public static final WoodType ORANGE_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_holly"), BlockSetType.OAK);
    public static final WoodType PINK_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_holly"), BlockSetType.OAK);
    public static final WoodType PURPLE_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_holly"), BlockSetType.OAK);
    public static final WoodType RED_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_holly"), BlockSetType.OAK);
    public static final WoodType WHITE_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_holly"), BlockSetType.OAK);
    public static final WoodType YELLOW_HOLLY = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_holly"), BlockSetType.OAK);
    //CHANTERELLE
    public static final WoodType BLACK_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_chanterelle"), BlockSetType.OAK);
    public static final WoodType BLUE_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_chanterelle"), BlockSetType.OAK);
    public static final WoodType BROWN_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_chanterelle"), BlockSetType.OAK);
    public static final WoodType CYAN_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_chanterelle"), BlockSetType.OAK);
    public static final WoodType GRAY_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_chanterelle"), BlockSetType.OAK);
    public static final WoodType GREEN_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_chanterelle"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_chanterelle"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_chanterelle"), BlockSetType.OAK);
    public static final WoodType LIME_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_chanterelle"), BlockSetType.OAK);
    public static final WoodType MAGENTA_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_chanterelle"), BlockSetType.OAK);
    public static final WoodType ORANGE_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_chanterelle"), BlockSetType.OAK);
    public static final WoodType PINK_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_chanterelle"), BlockSetType.OAK);
    public static final WoodType PURPLE_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_chanterelle"), BlockSetType.OAK);
    public static final WoodType RED_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_chanterelle"), BlockSetType.OAK);
    public static final WoodType WHITE_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_chanterelle"), BlockSetType.OAK);
    public static final WoodType YELLOW_CHANTERELLE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_chanterelle"), BlockSetType.OAK);
    //ENOKI
    public static final WoodType BLACK_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_enoki"), BlockSetType.OAK);
    public static final WoodType BLUE_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_enoki"), BlockSetType.OAK);
    public static final WoodType BROWN_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_enoki"), BlockSetType.OAK);
    public static final WoodType CYAN_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_enoki"), BlockSetType.OAK);
    public static final WoodType GRAY_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_enoki"), BlockSetType.OAK);
    public static final WoodType GREEN_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_enoki"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_enoki"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_enoki"), BlockSetType.OAK);
    public static final WoodType LIME_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_enoki"), BlockSetType.OAK);
    public static final WoodType MAGENTA_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_enoki"), BlockSetType.OAK);
    public static final WoodType ORANGE_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_enoki"), BlockSetType.OAK);
    public static final WoodType PINK_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_enoki"), BlockSetType.OAK);
    public static final WoodType PURPLE_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_enoki"), BlockSetType.OAK);
    public static final WoodType RED_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_enoki"), BlockSetType.OAK);
    public static final WoodType WHITE_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_enoki"), BlockSetType.OAK);
    public static final WoodType YELLOW_ENOKI = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_enoki"), BlockSetType.OAK);
    //WARPED
    public static final WoodType BLACK_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_warped"), BlockSetType.OAK);
    public static final WoodType BLUE_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_warped"), BlockSetType.OAK);
    public static final WoodType BROWN_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_warped"), BlockSetType.OAK);
    public static final WoodType CYAN_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_warped"), BlockSetType.OAK);
    public static final WoodType GRAY_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_warped"), BlockSetType.OAK);
    public static final WoodType GREEN_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_warped"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_warped"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_warped"), BlockSetType.OAK);
    public static final WoodType LIME_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_warped"), BlockSetType.OAK);
    public static final WoodType MAGENTA_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_warped"), BlockSetType.OAK);
    public static final WoodType ORANGE_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_warped"), BlockSetType.OAK);
    public static final WoodType PINK_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_warped"), BlockSetType.OAK);
    public static final WoodType PURPLE_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_warped"), BlockSetType.OAK);
    public static final WoodType RED_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_warped"), BlockSetType.OAK);
    public static final WoodType WHITE_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_warped"), BlockSetType.OAK);
    public static final WoodType YELLOW_WARPED = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_warped"), BlockSetType.OAK);
    //CRIMSON
    public static final WoodType BLACK_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_crimson"), BlockSetType.OAK);
    public static final WoodType BLUE_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_crimson"), BlockSetType.OAK);
    public static final WoodType BROWN_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_crimson"), BlockSetType.OAK);
    public static final WoodType CYAN_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_crimson"), BlockSetType.OAK);
    public static final WoodType GRAY_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_crimson"), BlockSetType.OAK);
    public static final WoodType GREEN_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_crimson"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_crimson"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_crimson"), BlockSetType.OAK);
    public static final WoodType LIME_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_crimson"), BlockSetType.OAK);
    public static final WoodType MAGENTA_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_crimson"), BlockSetType.OAK);
    public static final WoodType ORANGE_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_crimson"), BlockSetType.OAK);
    public static final WoodType PINK_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_crimson"), BlockSetType.OAK);
    public static final WoodType PURPLE_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_crimson"), BlockSetType.OAK);
    public static final WoodType RED_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_crimson"), BlockSetType.OAK);
    public static final WoodType WHITE_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_crimson"), BlockSetType.OAK);
    public static final WoodType YELLOW_CRIMSON = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_crimson"), BlockSetType.OAK);
    //OAK
    public static final WoodType BLACK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_oak"), BlockSetType.OAK);
    public static final WoodType BLUE_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_oak"), BlockSetType.OAK);
    public static final WoodType BROWN_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_oak"), BlockSetType.OAK);
    public static final WoodType CYAN_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_oak"), BlockSetType.OAK);
    public static final WoodType GRAY_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_oak"), BlockSetType.OAK);
    public static final WoodType GREEN_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_oak"), BlockSetType.OAK);
    public static final WoodType LIGHT_BLUE_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_oak"), BlockSetType.OAK);
    public static final WoodType LIGHT_GRAY_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_oak"), BlockSetType.OAK);
    public static final WoodType LIME_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_oak"), BlockSetType.OAK);
    public static final WoodType MAGENTA_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_oak"), BlockSetType.OAK);
    public static final WoodType ORANGE_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_oak"), BlockSetType.OAK);
    public static final WoodType PINK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_oak"), BlockSetType.OAK);
    public static final WoodType PURPLE_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_oak"), BlockSetType.OAK);
    public static final WoodType RED_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_oak"), BlockSetType.OAK);
    public static final WoodType WHITE_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_oak"), BlockSetType.OAK);
    public static final WoodType YELLOW_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_oak"), BlockSetType.OAK);
    //SPRUCE
    public static final WoodType BLACK_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_spruce"), BlockSetType.SPRUCE);
    public static final WoodType BLUE_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_spruce"), BlockSetType.SPRUCE);
    public static final WoodType BROWN_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_spruce"), BlockSetType.SPRUCE);
    public static final WoodType CYAN_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_spruce"), BlockSetType.SPRUCE);
    public static final WoodType GRAY_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_spruce"), BlockSetType.SPRUCE);
    public static final WoodType GREEN_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_spruce"), BlockSetType.SPRUCE);
    public static final WoodType LIGHT_BLUE_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_spruce"), BlockSetType.SPRUCE);
    public static final WoodType LIGHT_GRAY_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_spruce"), BlockSetType.SPRUCE);
    public static final WoodType LIME_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_spruce"), BlockSetType.SPRUCE);
    public static final WoodType MAGENTA_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_spruce"), BlockSetType.SPRUCE);
    public static final WoodType ORANGE_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_spruce"), BlockSetType.SPRUCE);
    public static final WoodType PINK_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_spruce"), BlockSetType.SPRUCE);
    public static final WoodType PURPLE_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_spruce"), BlockSetType.SPRUCE);
    public static final WoodType RED_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_spruce"), BlockSetType.SPRUCE);
    public static final WoodType WHITE_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_spruce"), BlockSetType.SPRUCE);
    public static final WoodType YELLOW_SPRUCE = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_spruce"), BlockSetType.SPRUCE);
    //ACACIA
    public static final WoodType BLACK_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_acacia"), BlockSetType.ACACIA);
    public static final WoodType BLUE_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_acacia"), BlockSetType.ACACIA);
    public static final WoodType BROWN_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_acacia"), BlockSetType.ACACIA);
    public static final WoodType CYAN_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_acacia"), BlockSetType.ACACIA);
    public static final WoodType GRAY_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_acacia"), BlockSetType.ACACIA);
    public static final WoodType GREEN_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_acacia"), BlockSetType.ACACIA);
    public static final WoodType LIGHT_BLUE_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_acacia"), BlockSetType.ACACIA);
    public static final WoodType LIGHT_GRAY_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_acacia"), BlockSetType.ACACIA);
    public static final WoodType LIME_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_acacia"), BlockSetType.ACACIA);
    public static final WoodType MAGENTA_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_acacia"), BlockSetType.ACACIA);
    public static final WoodType ORANGE_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_acacia"), BlockSetType.ACACIA);
    public static final WoodType PINK_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_acacia"), BlockSetType.ACACIA);
    public static final WoodType PURPLE_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_acacia"), BlockSetType.ACACIA);
    public static final WoodType RED_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_acacia"), BlockSetType.ACACIA);
    public static final WoodType WHITE_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_acacia"), BlockSetType.ACACIA);
    public static final WoodType YELLOW_ACACIA = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_acacia"), BlockSetType.ACACIA);
    //DARK_OAK
    public static final WoodType BLACK_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "black_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType BLUE_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "blue_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType BROWN_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "brown_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType CYAN_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "cyan_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType GRAY_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "gray_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType GREEN_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "green_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType LIGHT_BLUE_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_blue_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType LIGHT_GRAY_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "light_gray_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType LIME_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "lime_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType MAGENTA_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "magenta_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType ORANGE_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "orange_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType PINK_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "pink_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType PURPLE_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "purple_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType RED_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "red_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType WHITE_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "white_dark_oak"), BlockSetType.DARK_OAK);
    public static final WoodType YELLOW_DARK_OAK = WoodTypeRegistry.register(new Identifier(NormalityMod.MOD_ID, "yellow_dark_oak"), BlockSetType.DARK_OAK);

}
